<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Science 9: &quot;Vibrations&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Science</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/science/Vibrations/index.php" title="Challenge: &quot;Vibrations&quot;"><span>Vibrations</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Science-challenge" src="/files/images/groupmasters/11_all.gif" height="18" width="25" /><span>Science 9: &quot;Vibrations&quot; [made by <a class="fromuser" href="/userstats.php?username=Plasmator">Plasmator</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=339" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=29&amp;challenge_id=339" title="Visit the Science-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Science-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=339" title="79 users have solved this challenge so far.">[79]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Determine the motion of this mechanical system
<div class="challenge_1" style="text-align:center;"><img class="challenge_1" src="Spring.png" alt="Vibrations" /></div>
satisfying the initial conditions
<p class="challenge_1" style="text-align:center;">y<sub>1</sub>(0) = 1<br>y<sub>2</sub>(0) = 2<br>y<sub>1</sub>'(0) = -2*sqrt(6)<br>y<sub>2</sub>'(0) = sqrt(6)</p>
Hint: there are 4 different methods you can use to solve this problem. They all give the same exact result.<br />When you find the valid equations for y<sub>1</sub>(t) and y<sub>2</sub>(t) put them together like A_B and submit.<br />Good Luck !!!
<form action="/challenges/science/Vibrations/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>