<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>/dev/null 3: &quot;Yes Yes!&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>/dev/null</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/crypt_yesyes/index.php" title="Challenge: &quot;Yes Yes!&quot;"><span>Yes Yes!</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a /dev/null-challenge" src="/files/images/groupmasters/13_all.gif" height="18" width="25" /><span>/dev/null 3: &quot;Yes Yes!&quot; [made by <a class="fromuser" href="/userstats.php?username=|MasterMind|">|MasterMind|</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=135" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=48&amp;challenge_id=135" title="Visit the /dev/null-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the /dev/null-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=135" title="504 users have solved this challenge so far.">[504]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Yes!<p class="challenge_mono_1" style="text-align:center;">B3546D82F7467AEDB0280BCF2913CFFC6835B51A<br />BF1A58D41672F2F1CE7635218C71573EEA8EBDFC<br />15DC394AC902BE1BB1E52ABF2ECE13975929978D<br />557AD8175E7A30B18CE334D3107D61FEEF3D8CF0<br />F58761A9845BCEBDA100C7A18DDD12B515C444F0<br />BF1A58D41672F2F1CE7635218C71573EEA8EBDFC<br />1104E9C8914855B67E469EB69055BC8AE7A2A92B<br />5DD4DB394AF22DD2C6BAA69902D1F9B17D89F88E</p>Yes!<p class="challenge_mono_1" style="text-align:center;">1=617CFD8764E89EC37575A1C9CBA627BE68309220<br />2=2ED5267014A335E508B2F099769CA3278FFD070F</p>
<form action="/challenges/crypt_yesyes/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>