<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Information Gathering 1: &quot;Research - Google is your friend&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Information Gathering</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/internet_research/research.php" title="Challenge: &quot;Research - Google is your friend&quot;"><span>Research - Google is your friend</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Information Gathering-challenge" src="/files/images/groupmasters/12_all.gif" height="18" width="25" /><span>Information Gathering 1: &quot;Research - Google is your friend&quot; [made by <a class="fromuser" href="/userstats.php?username=AlGo">AlGo</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=107" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=42&amp;challenge_id=107" title="Visit the Information Gathering-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Information Gathering-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=107" title="282 users have solved this challenge so far.">[282]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="width:100%;margin:0px;padding:0px;text-align:justify;">
In the last 50 years, two films have been done based on a novel by a russian-american writer (yes, both films about the same novel). One of these movies was filmed by a really famous director who died in the late 90's. The writer of the novel also participated in this screenplay. The other film starred one famous English actor who put a voice in &quot;The Lion king&quot; movie from 1994.
<p class="challenge_1" style="text-align:left;">- What is the title of the novel?</p>
And, now that you've searched for the lion king, 
<p class="challenge_1" style="text-align:left;">- Who was the character this actor put the voice to?</p>
In the novel (the one from the russian american writer, not the lion king ;-)), there's a character whose name is an anagram of the writer.
<p class="challenge_1" style="text-align:left;">- Who is the writer and who is that character?</p>
Now I want some info about the movie by the important director (the good one, the other isn't really good... ;-))
<p class="challenge_1" style="text-align:left;">- What year was it released?<br />- Who were the actor and the actress who did the main roles? (Oh, you haven't read the book nor seen the movies. Well, that's a problem my friend, but I'm sure you can find them anyway...)</p>
Before this film, that actor did a romans movie.<p class="challenge_1" style="text-align:left;">- What's its title?<br />
- That romans movie is based on a play by who?</p>This writer died most likely the same day that another writer from another country did.<p class="challenge_1" style="text-align:left;">- Who is that writer?<br />
- What's is most known book?<br />
- Who is the main character?<br /> 
- And the real name of that character?</p>
And the last question, the hardest one if you don't know where to look, but quite easy if you know the right place.<br />Let's get back to the films we were talking about in the begining. I want you to look at the release year of the newest of the two films. That year, Dylan (Bob or Jakob, I won't tell you) released an original new album (that is, no reissues, no special editions, no single, just a new album). In fact, I wouldn't be asking this if it wasn't because that album is my favourite one (so you can blame Mr Dylan for this last question).<p class="challenge_1" style="text-align:left;">In that album, there's only ONE song that is in the key of Ab minor, tell me the title and you're done.</p>
<a class="challenge_1" href="/forum/forum_newtopic.php?forumid=50&amp;challenge=107">Post your answers here!</a></div>
</div></div></body></html>