<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Crypto 27: &quot;The Treasure&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"><style type="text/css">
  span.i {font-style:italic;}
</style>
</head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Crypto</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/crypto32/index.php" title="Challenge: &quot;The Treasure&quot;"><span>The Treasure</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Crypto-challenge" src="/files/images/groupmasters/3_all.gif" height="18" width="25" /><span>Crypto 27: &quot;The Treasure&quot; [made by <a class="fromuser" href="/userstats.php?username=RogerFanMorvill">RogerFanMorvill</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=123" title="Rate this challenge!"><img src="/files/images/icons/vote_stat_sl.gif" width="16" height="16" alt="vote icon" title="Rate this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=20&amp;challenge_id=123" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=32&amp;challenge_id=123" title="Visit the Crypto-Forum for solutions of this challenge."><img src="/files/images/misc/challenge_forum_solutions.gif" width="16" height="16" alt="forum icon" title="Visit the Crypto-Forum for solutions of this challenge." /><span>Solutions</span></a></td><td class="done">done&nbsp;<a href="/challengestats.php?challengeid=123" title="191 users have solved this challenge so far.">[191]</a></td></tr></table></td></tr></table></div><div class="challenge_div">There is a treasure to discover in the town of Buford (Virginia, USA). More than $ 30 million in gold; they wait for you :-) 
<p class="challenge_1" style="text-align:center;">12-19-30-41-1-1-21-<span class="i">3</span>-39-8-1-9-3-20-<span class="i">2</span>-2-8-27-8-16-30-19-1-10-30-3-24-17-2-3-3-11-29-<span class="i">3</span>-2-19-7-17-<span class="i">2</span>-4-8-27-7-3-22-4-12-7-30-1-10-21-1-4-1-12-18-1-20-<span class="i">1</span>-7-8-4-7-3-3-11-7-1-19-4-24-1-30-4-29-<span class="i">3</span>-1-19-7-18-6-18-14-12-1-5-13-4-12-24-2-9-11-10-7-8-4-7-3-3-8-22-6-12-19-19-4-11-<span class="i">1</span>-1-19-3-8-2-6-1-9-3-9-2-3-6-23-<span class="i">4</span>-11-22-8-12-8-12-2-5-1-5-11-9-3-14-<span class="i">2</span>-3-12-7-30-1-2-19-12-8-15-<span class="i">2</span>-1-9-9</p>There are documents that are not limited only to one country...
<form action="/challenges/crypto32/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>