<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Logic 9: &quot;Party time!&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Logic</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/logic8/index.php" title="Challenge: &quot;Party time!&quot;"><span>Party time!</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Logic-challenge" src="/files/images/groupmasters/9_all.gif" height="18" width="25" /><span>Logic 9: &quot;Party time!&quot; [made by <a class="fromuser" href="/userstats.php?username=iloveallison">iloveallison</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=96" title="Rate this challenge!"><img src="/files/images/icons/vote_stat_sl.gif" width="16" height="16" alt="vote icon" title="Rate this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=26&amp;challenge_id=96" title="Visit the Logic-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Logic-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=38&amp;challenge_id=96" title="Visit the Logic-Forum for solutions of this challenge."><img src="/files/images/misc/challenge_forum_solutions.gif" width="16" height="16" alt="forum icon" title="Visit the Logic-Forum for solutions of this challenge." /><span>Solutions</span></a></td><td class="done">done&nbsp;<a href="/challengestats.php?challengeid=96" title="1415 users have solved this challenge so far.">[1415]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Four students arrived at the party driving colorful cars. The students were Alan, Betty, Charlie, and Denise.<p class="challenge_1" style="text-align:center;">From the following statements, of which all are true, can you tell the order of arrival and the color of each student's car?<br />The colors of the cars are blue, gold, purple, and white.</p>
1. The four students were Charlie, the student who arrived second, the student with a white car, and Alan.<br />
2. Charlie did not arrive first, and Denise was not the student who arrived just before him.<br />
3. Denise's car was not white.<br />
4. Betty arrived just before the student whose car was blue, who was not Charlie.<br />
5. Alan's car was not purple.
<p class="challenge_1" style="text-align:center;"><a class="challenge_2" href="/forum/forum_newtopic.php?forumid=50&amp;challenge=96">Post your solution with explanation here!</a></p>
</div></div></body></html>