<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Stegano 54: &quot;The Friendly Hobo&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Stegano</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/stegano/The_Friendly_Hobo/index.php" title="Challenge: &quot;The Friendly Hobo&quot;"><span>The Friendly Hobo</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Stegano-challenge" src="/files/images/groupmasters/5_all.gif" height="18" width="25" /><span>Stegano 54: &quot;The Friendly Hobo&quot; [made by <a class="fromuser" href="/userstats.php?username=BaRa">BaRa</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=319" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=22&amp;challenge_id=319" title="Visit the Stegano-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Stegano-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=319" title="24 users have solved this challenge so far.">[24]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Find the word, it's written on the picture.<BR>
<div class="challenge_1" style="text-align:center;padding:0px;"><img src="Hobo.png" class="challenge_2" title="The Friendly Hobo." alt="The Friendly Hobo" /></div>
<form action="/challenges/stegano/The_Friendly_Hobo/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form>Copyright © 2005 BaRa
</div></div></body></html>