<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Programming 8: &quot;The Blacksheep Story Part II&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Programming</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/programming/caesum_2/index.php" title="Challenge: &quot;The Blacksheep Story Part II&quot;"><span>The Blacksheep Story Part II</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Programming-challenge" src="/files/images/groupmasters/7_all.gif" height="18" width="25" /><span>Programming 8: &quot;The Blacksheep Story Part II&quot; [made by <a class="fromuser" href="/userstats.php?username=Caesum">Caesum</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=156" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=24&amp;challenge_id=156" title="Visit the Programming-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Programming-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=156" title="137 users have solved this challenge so far.">[137]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><p class="challenge_1" style="text-align:left;">The Blacksheep Story Part II</p>
<div style="text-align:left;margin:px;padding:0px;">
Blacksheep has finally reconfigured the TBS network with fibreoptics and it is running very well. With all of this hardware in place he is running the latest in online gaming experiences with the virtual reality multi-player treasure hunt. Blacksheep himself has designed the levels. The idea is very simple, you have to move around a maze and collect the treasures and then make your way to the exit. Your score is based on the amount of energy that you expended.
<div style="padding:0px;margin:2mm;">
<img src="sample.jpg" class="challenge_1" style="float:left;margin-right:2mm;" />
You begin at the square marked start and can move in one of four directions (up, down, left or right as you look at the map) and each move expends one energy point. Now you will see that each treasure has two numbers attached to it. The first is the pickup cost of the treasure and the second is the carrying cost of the treasure. Once you have picked a treasure up you cannot put it back down again. The pickup cost is added when the treasure is picked up, and the carrying cost is added for each move that is made once you have that treasure picked up. Some treasures are much heavier than others and so you will expend more energy as you carry these around the maze.<br /><br /><span style="font-weight:bold;text-decoration:underline;">Here is a small example:</span><br />From the start you can move down two squares (cost 2), pick up the first treasure (cost 3), move right two squares (cost 10, as movement cost is now 1 plus 4 for carrying the first treasure), pickup the second treasure (cost 7) and move up two squares (cost 26 = (1+4+8)*2), for a total cost of 48. This is the most efficient route on the map.</div>
<p style="margin:0px;padding:0px;clear:both;">Now Blacksheep needs to know what the theoretical best scores are for his levels so that he can work out how efficient a player has been. This is your task, and the levels are <a href="level1.jpg" class="challenge_1">here</a> and <a href="level2.jpg" class="challenge_1">here</a>.<br />When you have the two answers the final answer is a_b, so if the answers are 100 and 200 then you will enter &quot;100_200&quot;.</p><div class="challenge_1" style="text-align:center;font-weight:bold;font-size:14pt;">Good luck!</div>
</div>
<form action="/challenges/programming/caesum_2/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>