<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Crypto 52: &quot;Crypto Training Programme&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Crypto</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/crypto/caesum_training/index.php" title="Challenge: &quot;Crypto Training Programme&quot;"><span>Crypto Training Programme</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Crypto-challenge" src="/files/images/groupmasters/3_all.gif" height="18" width="25" /><span>Crypto 52: &quot;Crypto Training Programme&quot; [made by <a class="fromuser" href="/userstats.php?username=Caesum">Caesum</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=229" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=20&amp;challenge_id=229" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=229" title="47 users have solved this challenge so far.">[47]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="margin:0px;padding:0px;text-align:left;">
<p class="challenge_1" style="text-align:left;">Welcome to crypto our crypto training programme.</p>
Our listening post intercepted the following two messages within a short space of time. They were both sent from the same operative to two different people. We believe that these messages are in fact the same message.<br />
Furthermore the operatives are known to use vigenere encryptions although with mixed cipher alphabets. We await your analysis, the answer will be the last two words of the decrypted text.<br /><br />
Message 1:
<div class="challenge_mono_1"><table cellspacing="0" style="margin:0px;"><tr><td style="text-align:left;padding:0px;color:#FFAA00;font-size:10pt;">axiop xgxsx aqmpw qhfih vpvoe qgbcz rafpg rfnef gagmo qpvwu toiqy scinf ihvuf yllys jaato gsdgp aqlew zttin faevc szbuq iubpb cyorl yyosa wrzof fldjl qfbas jzjaq mshxs aaoxf mkvup hhpbj mahrz hxzap nybcy dkily cszps nbpzu cbbvp kkaps qukqb rlkfg terfu kvufi ayjnp ttvfc qnsil laqzt dnngk ifoov akfow osjav vinvp vguqp ichob pgkaq znqks oevel cpjmt</td></tr></table></div>
Message 2:
<div class="challenge_mono_1"><table cellspacing="0" style="margin:0px;"><tr><td style="text-align:left;padding:0px;color:#FFAA00;font-size:10pt;">dawwk wwbgv zhtie sgsfk iirot hklpf hfofi vgztp aemyz llrzy dxafr xzhzf ermwu vsjfz tyezk gmcaf senxq hmtgz bucjh ztzni bsfhj eugmg fzgcv otylu cnhkd glpfx hokeq zzohi jztwd pfiue nifad xahpw mmxlc ayqta tncnq qfijm zqkhk ngixo jnzzv unpjm zohpe ttxqp xzssc llalh hjegx tkgat upcdu jwcaz yfasm hqqax gztyh hantd eaxes qxjbb auwun sfsqx fthvw ldawp</td></tr></table></div>
<span style="font-weight:bold;">What are the last two words of the message ?</span>
<form action="/challenges/crypto/caesum_training/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div>
</div></div></body></html>