<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Crypto 59: &quot;Crypto Square(s)&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Crypto</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/crypto/velo_squares/index.php" title="Challenge: &quot;Crypto Square(s)&quot;"><span>Crypto Square(s)</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Crypto-challenge" src="/files/images/groupmasters/3_all.gif" height="18" width="25" /><span>Crypto 59: &quot;Crypto Square(s)&quot; [made by <a class="fromuser" href="/userstats.php?username=velo">velo</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=274" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=20&amp;challenge_id=274" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Crypto-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=274" title="44 users have solved this challenge so far.">[44]</a></td></tr></table></td></tr></table></div><div class="challenge_div">When you got some readable text, you'll know that the second part begins...
<br />-- There is no need for using a PC, programs, hints or keys --
<p class="challenge_1" style="text-align:center;">WTGYU AGVSW FSSGY EESLT MIEAI OOLOS LNTED JCNNL RLAOO LCLEO UTODL EABDP TEETN SHRTB ITETL HHTCO TITHE FELHA EITAT UNWEN OTEEY RDENU SKESE RHDJI EDRFS EALOA GEAOT IESIE YBVLR ELSBN SNSNP OOEUY TEOIO AAODR UUHTO TTNSW SMOIO RTOIU RTEEB EONTG LSUOB YEOAY NNLOR OERNE IRFSE</p>
<form action="/challenges/crypto/velo_squares/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>