<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Logic 12: &quot;Mmmmm... candies!&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Logic</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/logic_prices/index.php" title="Challenge: &quot;Mmmmm... candies!&quot;"><span>Mmmmm... candies!</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Logic-challenge" src="/files/images/groupmasters/9_all.gif" height="18" width="25" /><span>Logic 12: &quot;Mmmmm... candies!&quot; [made by <a class="fromuser" href="/userstats.php?username=Halamantariel">Halamantariel</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=195" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=26&amp;challenge_id=195" title="Visit the Logic-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Logic-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=195" title="606 users have solved this challenge so far.">[606]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Find out the price of the chocolate...
<div class="challenge_1" style="text-align:center;padding:0px;"><img src="prices.png" alt="Logic by Halamantariel" class="challenge_1" style="border-style:solid;border-left-width:1px;border-top-width:0px;border-right-width:1px;border-bottom-width:0px;border-color:#FFFFFF;margin:0px;" /></div>
Post the solution and a description of how to find it <a class="challenge_1" href="/forum/forum_newtopic.php?forumid=50&amp;challenge=195">here!</a>
</div></div></body></html>