<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Information Gathering 5: &quot;Cure Sheep&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Information Gathering</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/internet/bara_2/index.php" title="Challenge: &quot;Cure Sheep&quot;"><span>Cure Sheep</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Information Gathering-challenge" src="/files/images/groupmasters/12_all.gif" height="18" width="25" /><span>Information Gathering 5: &quot;Cure Sheep&quot; [made by <a class="fromuser" href="/userstats.php?username=BaRa">BaRa</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=230" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=42&amp;challenge_id=230" title="Visit the Information Gathering-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Information Gathering-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=230" title="173 users have solved this challenge so far.">[173]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="text-align:justify;margin-left:0px;margin-top:0px;margin-right:0px;margin-bottom:1mm;padding-left:0px;padding-right:0px;padding-top:0px;padding-bottom:1.5mm;border-style:dashed;border-color:#4040A0;border-width:0px 0px 1px;">
One year ago I bought a little lamb to keep as a pet (in the garden ofcourse) for the children. My littlest decided to name the animal &quot;Sheep&quot;, I know not very creative but hey, he's only 3 years old. Now, recently Sheep got ill. We've taken it to the veterinary, but the doctor couldn't figure out what the problem was. Now we are three weeks later and Sheep is still ill, and he's deteriorating very fast. The only thing we can hope for is that we can find a specialist who can determine what's wrong.
</div>
<span style="font-weight:bold;">Are you that specialist?</span>
<form action="/challenges/internet/bara_2/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form>Copyright © 2004 BaRa
</div></div></body></html>
