<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Science 7: &quot;Circles&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Science</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/science/circles/index.php" title="Challenge: &quot;Circles&quot;"><span>Circles</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Science-challenge" src="/files/images/groupmasters/11_all.gif" height="18" width="25" /><span>Science 7: &quot;Circles&quot; [made by <a class="fromuser" href="/userstats.php?username=abogado">abogado</a> and <a class="fromuser" href="/userstats.php?username=michstreet">michstreet</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=290" title="Rate this challenge!"><img src="/files/images/icons/vote_stat_sl.gif" width="16" height="16" alt="vote icon" title="Rate this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=29&amp;challenge_id=290" title="Visit the Science-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Science-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=40&amp;challenge_id=290" title="Visit the Science-Forum for solutions of this challenge."><img src="/files/images/misc/challenge_forum_solutions.gif" width="16" height="16" alt="forum icon" title="Visit the Science-Forum for solutions of this challenge." /><span>Solutions</span></a></td><td class="done">done&nbsp;<a href="/challengestats.php?challengeid=290" title="280 users have solved this challenge so far.">[280]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="margin:0px;padding:0px;text-align:left;">
Consider a circle whose center is (2,2) and whose radius is 1, and the straight line that goes through the origin and that is tangent to this circle so that the intersection between them is as shown in the picture below.With this new point we make a new circle whose radius is half of the first one, and we calculate the corresponding intersection point with the same suppositions as in the first case.We repeat the process to the infinite.
Find the distance between the center of the circle in the infinite and the origin (point (0,0)).
<div class="challenge_1" style="text-align:center;padding:0px;"><img src="circles.jpg" alt="the tent" style="margin:0px;text-align:center;border-style:solid;border-color:#FFFFFF;border-left-width:1px;border-top-width:0px;border-right-width:1px;border-bottom-width:0px;" /></div></div>
<form action="/challenges/science/circles/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>