<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Special 24: &quot;Bank Fraud&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Special</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/specials/bankfraud/index.php" title="Challenge: &quot;Bank Fraud&quot;"><span>Bank Fraud</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Special-challenge" src="/files/images/groupmasters/10_all.gif" height="18" width="25" /><span>Special 24: &quot;Bank Fraud&quot; [made by <a class="fromuser" href="/userstats.php?username=rayden5">rayden5</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=283" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=27&amp;challenge_id=283" title="Visit the Special-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Special-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=283" title="37 users have solved this challenge so far.">[37]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="text-align:justify;margin:0px;padding:0px;"><p class="challenge_1" style="text-align:left;">Level I - Hi there, welcome to the Challenge!</p> 
This time you will have to solve 3 levels. One level is cheese, the next one is also easy but may by hard for some guys here, and level 3 is the real challenge.<br />
You are some Uberl33t H@XX0r (like usual) and you want to check out online bank fraud. You know about a banks' customer called &quot;Peter Parker&quot;. Peter has already uploaded a &quot;Digital Online Ticket&quot; which he wants to use to transfer some money from his account to another one. Your intension is to get the ticket, change the account number to your own one (and maybe the ammount *G*) and then finally approve the faked ticket. Details will follow soon :-)<br />
Ok now go to Peters personal Banks Page where he already uploaded this ticket...
</div><p class="challenge_1" style="text-align:center;"><a class="challenge_2" href="level1.zip">Here at level1 you will find the filename of the page.</a></p>
</div></div></body></html>