<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Special 26: &quot;ReverseMe 2&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Special</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/specials/bb_reverseme/index.php" title="Challenge: &quot;ReverseMe 2&quot;"><span>ReverseMe 2</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Special-challenge" src="/files/images/groupmasters/10_all.gif" height="18" width="25" /><span>Special 26: &quot;ReverseMe 2&quot; [made by <a class="fromuser" href="/userstats.php?username=bb">bb</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=316" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=27&amp;challenge_id=316" title="Visit the Special-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Special-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=316" title="12 users have solved this challenge so far.">[12]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Finally, the challenge we've all been waiting for! :) :)<BR>
Please send all solutions to: dispacct@hotmail.com<BR>
Make sure the subject is like this: TBSReverseme - USERNAME<BR>
Also, like the first one, keep in mind that I check the executable on a Windows XP(tm) machine, so make sure it works :).
<p class="challenge_1" style="text-align:center;">
<a class="challenge_2" href="/challenges/specials/bb_reverseme/reverseme.zip">Download the File</a>
</p>
</div></div></body></html>