<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Stegano 42: &quot;Target-Identification&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Stegano</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/stegano/targetidentification/index.php" title="Challenge: &quot;Target-Identification&quot;"><span>Target-Identification</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Stegano-challenge" src="/files/images/groupmasters/5_all.gif" height="18" width="25" /><span>Stegano 42: &quot;Target-Identification&quot; [made by <a class="fromuser" href="/userstats.php?username=BaRa">BaRa</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=247" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=22&amp;challenge_id=247" title="Visit the Stegano-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Stegano-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=247" title="52 users have solved this challenge so far.">[52]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Introduction:
<p class="challenge_1" style="text-align:justify;">After tracing a phonecall the CIA busted into an old house where the famous hitman with the alias Benedicto was resident for the last 2 weeks. They have searched the whole house and found one piece of evidence: a half burned letter. What they have discovered is that this letter came from a person called J.Q., which is the consigliere of a local mob boss.<br />
A picture was mentioned in the letter, but unfortunatly it is completely destroyed. The CIA have send the leftovers to a lab of Fujifilm and they tagged the picture as polaroid. They also mentioned that the image of burned polaroid pictures can be recovered by stenographers.</p>
Mission:
<p class="challenge_1" style="text-algin:justify;">Can you recover the picture and ID the person who's it? It's a matter of life and death! Once you have found the identity please send it to us in the following format: &quot;First name&quot; + &quot;Last name&quot; + &quot;Birthyear&quot;. (JohnDoe1975)</p>
Letter:
<div class="challenge_1" style="text-align:center;padding:0px;"><img src="TheLetter.png" width="213" height="280" alt="the stegano" title="The stegano - &quot;Target-Identification&quot;" style="margin:0px;text-align:center;border-style:solid;border-width:0px 1px;border-color:#FFFFFF;" /></div>
<form action="/challenges/stegano/targetidentification/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form>Copyright © 2004 BaRa
</div></div></body></html>