<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>/dev/null 1: &quot;Only an easy text crypto.&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>/dev/null</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/levelc6/textcrypto.php" title="Challenge: &quot;Only an easy text crypto.&quot;"><span>Only an easy text crypto.</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a /dev/null-challenge" src="/files/images/groupmasters/13_all.gif" height="18" width="25" /><span>/dev/null 1: &quot;Only an easy text crypto.&quot;</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=16" title="Rate this challenge!"><img src="/files/images/icons/vote_stat_sl.gif" width="16" height="16" alt="vote icon" title="Rate this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=48&amp;challenge_id=16" title="Visit the /dev/null-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the /dev/null-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=49&amp;challenge_id=16" title="Visit the /dev/null-Forum for solutions of this challenge."><img src="/files/images/misc/challenge_forum_solutions.gif" width="16" height="16" alt="forum icon" title="Visit the /dev/null-Forum for solutions of this challenge." /><span>Solutions</span></a></td><td class="done">done&nbsp;<a href="/challengestats.php?challengeid=16" title="2457 users have solved this challenge so far.">[2457]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Get the solution out of this text:
<p class="challenge_1" style="text-align:justify;">cross-Site scripting (xss) vulnerabilities are very often misunderstood and not given the due concern and Attention they deserve by vendors. xss is the preferred acronym for “cross-site scripting” simply to Minimize the confusion with cascading style sheets (css). simply put, a web application vulnerable to xss allows a user to inadvertently send malicious data to him or herself through that application. attackers often perform xss exploitation By crafting malicious urls and tricking users into clicking on them. these links cause client side scripting languages (vbscript, javascript, etc.) of the Attacker’s choice to execute on the victim’s browser. xss vulnerabilities are caused by a failure in the web application to properly validate user input.</p>
<form action="/challenges/levelc6/textcrypto.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>