<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Programming 7: &quot;The Blacksheep Story Part I&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Programming</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/programming/caesum_1/index.php" title="Challenge: &quot;The Blacksheep Story Part I&quot;"><span>The Blacksheep Story Part I</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Programming-challenge" src="/files/images/groupmasters/7_all.gif" height="18" width="25" /><span>Programming 7: &quot;The Blacksheep Story Part I&quot; [made by <a class="fromuser" href="/userstats.php?username=Caesum">Caesum</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=154" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=24&amp;challenge_id=154" title="Visit the Programming-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Programming-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=154" title="185 users have solved this challenge so far.">[185]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><p class="challenge_1" style="text-align:left;">The Blacksheep Story Part I</p> 
<div style="margin:0px;padding:0px;text-align:left;">
Blacksheep has a problem that requires your programming expertise. He is redesigning the TBS network using the latest fibreoptics technology. This upgrade will enable TBS to run its network well into the millenium. Now the thing about fibreoptics is that cables enter router nodes and can be split only at those nodes, you can't just meet cables anywhere you want. Blacksheep does not want any more router nodes, and these are already fixed by physical location. The other thing about fibreoptics is that they are expensive. Because fibreoptics are so expensive Blacksheep wishes to minimise the cost. Blacksheep has already mapped out the network on a grid and identified all the router nodes on it. 
<div class="challenge_1" style="text-align:left;">Your task is to find the minimum length of fibreoptics that will connect all of the nodes together such that there exists a path between any two nodes on the grid. In case this is not clear here is an example:<div style="margin:2mm;padding:0px;text-align:center;"><img src="map_example.gif" class="challenge_1" style="margin-right:1cm;" /><img src="map_examplea.gif" class="challenge_1" /></div>As you can see there are 5 nodes and the minimum path is shown. It has length 17.31.</div>
Finally here is the map of the <a href="map.gif" class="challenge_1">TBS network</a>. You need to give the length to 9 significant figures (the grid is in 1 meter units, give your answer in meters).<div class="challenge_1" style="text-align:center;font-size:14pt;font-weight:bold;">Good luck!</div>
</div> 
<form action="/challenges/programming/caesum_1/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>