<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Special 6: &quot;Lord of the Runes&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Special</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/crypto30/crypto30.php" title="Challenge: &quot;Lord of the Runes&quot;"><span>Lord of the Runes</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Special-challenge" src="/files/images/groupmasters/10_all.gif" height="18" width="25" /><span>Special 6: &quot;Lord of the Runes&quot; [made by <a class="fromuser" href="/userstats.php?username=DeathSpawn">DeathSpawn</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=113" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=27&amp;challenge_id=113" title="Visit the Special-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Special-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=113" title="100 users have solved this challenge so far.">[100]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><p style="text-align:justify;padding:0px;margin:0px;">
You've been following the map for many a mile and the light grows dim. You must make camp but the Enchanted Forest lies ahead. You'd rather wait for morning, but the trees offer the only shelter from the driving rain.<br />You caustiously enter, fearing what you might find. You see ahead of you, the crop of rock marked on the old map, rising above the trees. At the base of the cliff, there stands a door, etched with strange symbols. You know that the road to greatness lies on the other side, but how to gain enterance? You must discover what the symbols mean...</p>
<div class="challenge_1" style="text-align:center;"><img src="ruined.jpg" alt="the runes again..." style="challenge_1" /></div>
<form action="/challenges/crypto30/crypto30.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>