<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Science 6: &quot;Lifespan&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Science</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/science/lifespan/index.php" title="Challenge: &quot;Lifespan&quot;"><span>Lifespan</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Science-challenge" src="/files/images/groupmasters/11_all.gif" height="18" width="25" /><span>Science 6: &quot;Lifespan&quot; [made by <a class="fromuser" href="/userstats.php?username=pjsk8">pjsk8</a>]</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=281" title="Rate this challenge!"><img src="/files/images/icons/vote_stat_sl.gif" width="16" height="16" alt="vote icon" title="Rate this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=29&amp;challenge_id=281" title="Visit the Science-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Science-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=40&amp;challenge_id=281" title="Visit the Science-Forum for solutions of this challenge."><img src="/files/images/misc/challenge_forum_solutions.gif" width="16" height="16" alt="forum icon" title="Visit the Science-Forum for solutions of this challenge." /><span>Solutions</span></a></td><td class="done">done&nbsp;<a href="/challengestats.php?challengeid=281" title="243 users have solved this challenge so far.">[243]</a></td></tr></table></td></tr></table></div><div class="challenge_div"><div style="margin:0px;padding:0px;text-align:left;">My insurance company forced me to take a new type of medical examination involving my DNA. With the recent completion of the Human Genome Project, scientists are SURE they can read your life through your DNA.<br />
However, when the results from my test came in, my boss &quot;regretfully&quot; informed me that they had to let me go. He didn't know what was wrong with me, he only told me that my DNA was unusually wide, meaning that the length of one turn of my DNA was longer than that of most humans. The doctors are almost positive that this will have a negative effect on my lifespan. My boss knows nothing of the length of my DNA. The only thing my boss told me was that the formula he used to determine this was:
<p class="challenge_1" style="text-align:center;">r(t) = b&middot;cos(t)&middot;i + b&middot;sin(t)&middot;j + (1-b<sup>2</sup>)<sup>1/2</sup>&middot;t&middot;k</p>
Can you help me find the length of one turn of my DNA?</div>
<form action="/challenges/science/lifespan/index.php" method="get" style="margin-top:3mm;margin-bottom:1mm;padding:0px;">
  <input type="text" value="enter solution" name="solution" size="20" class="challenge_edit" />
  <input type="submit" value="Check it!" name="button_submit" style="margin-left:5mm;" class="challenge_submit" />
</form></div></div></body></html>