<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<title>Flash 2: &quot;Flash #2&quot;</title>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="author" content="theblacksheep">
<link rel="stylesheet" type="text/css" href="/styles.css"></head><body class="usual"><div class="navline"><a href="/hackchallenge.php" title="Go to the challenge-list."><img src="/files/images/icons/list_small.gif" width="12" height="11" alt="icon" title="Go to the challenge-list." /><span>Challenges</span></a><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><span>Flash</span><img src="/files/images/misc/arrow_navline.gif" class="arrow" width="10" height="9" alt="-&gt;" title="" /><a href="/challenges/flash/goat/index.php" title="Challenge: &quot;Flash #2&quot;"><span>Flash #2</span></a></div><div class="module"><div class="chall_header"><table cellspacing="0"><tr><td class="info"><img class="grouppic" alt="a Flash-challenge" src="/files/images/groupmasters/6_all.gif" height="18" width="25" /><span>Flash 2: &quot;Flash #2&quot;</span></td><td class="links"><table cellspacing="0"><tr><td class="forum"><a href="/challvote.php?challid=255" title="See the rating of this challenge!"><img src="/files/images/icons/vote_stat_see_sl.gif" width="16" height="16" alt="vote icon" title="See the rating of this challenge!" /><span>Vote</span></a></td><td class="forum_space">&nbsp;</td><td class="forum"><a href="/forum/forum_showforum.php?forumid=23&amp;challenge_id=255" title="Visit the Flash-Forum to ask questions or to find hints for this challenge."><img src="/files/images/misc/challenge_forum_questions.gif" width="16" height="16" alt="forum icon" title="Visit the Flash-Forum to ask questions or to find hints for this challenge." /><span>Forum</span></a></td><td class="notdone">not&nbsp;done&nbsp;<a href="/challengestats.php?challengeid=255" title="171 users have solved this challenge so far.">[171]</a></td></tr></table></td></tr></table></div><div class="challenge_div">Good luck!
<div class="challenge_1" style="text-align:center;padding:0px;">
<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0" width="277" height="56" id="BS-Flash" style="text-align:center;margin:0px;border-style:solid;border-width:0px 1px;border-color:#FFFFFF;">
 <param name="movie" value="flashcrk.swf" />
 <param name="quality" value="high" />
 <param name="bgcolor" value="#404060" />
 <embed src="BS-Flash.swf" quality="high" bgcolor="#FFFFFF"  width="277" height="56" name="BS-Flash" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
</object></div>
</div></div></body></html>